services: 
  - type: web 
    name: car-price-prediction 
    env: python 
    plan: free 
    envVars: 
      - key: PYTHON_VERSION 
        value: 3.9.18 
    buildCommand: pip install -r requirements.txt 
    startCommand: gunicorn app:app 
